### ISSUE TITLE
Annotation group documentation

### ISSUE THREAD

**Issue by gaow** [xinhe-lab/mirage#1]
I got this email from a user: 

>  In my data analysis,  I got the result by using annovar anova. I found that you annotate with several popular programs including PolyPhen, CADD and SIFT.  In my data analysis, I will do this step before mirage analysis?   I read your code about mirage, there are four columns( format of input data column 1:variant, 2,NO.variant in cases 3. No variant in control 4 variant group index). but I do not know where these columns come from? can you teach me?

@han16 we wrote on [this page](https://xinhe-lab.github.io/mirage/articles/mwe.html) "Variant groups can be user defined, usually depending on its annotations." but it seems too vague to be helpful to users. Is it correct if we change it to the  following:  

"Variant groups can be user defined, usually depending on its annotations. For example, in Han et al (2019+), we label as group `2` those variants with PolyPhen 194 score greater than 0.957, CADD score top 10% or SIFT score < 0.05; other variants are labelled group `1`"

Is this correct?

**Comment by linnanqia** [comment]
Thank you for your response!  I still have four questions:
(1) No.case and  No.contr? where will I get it?
(2) in my data, there are two files including,Michi_filter_final_dup.exonic_variant_function and Michi_filter_final_dup.variant_function,  I think the first file I can use to generate the group index. right?
(3) I found in the exonic file, some of them are synonymous, some of them are nonsyonymous , and some said unkown. may I check nonsyonymous and unknown firstly? or just input all genes to CADD or polyphen?
(4) Mirage is for variant set and mirage-vs is for gene set. so firstly I ran mirage and found that there are 150(in your paper) variants set, and then run mirage-VS just like your paper did?
Thank you!
Best!
Haizhu

**Comment by han16** [comment]
> Thank you for your response! I still have four questions:
> (1) No.case and No.contr? where will I get it?
> (2) in my data, there are two files including,Michi_filter_final_dup.exonic_variant_function and Michi_filter_final_dup.variant_function, I think the first file I can use to generate the group index. right?
> (3) I found in the exonic file, some of them are synonymous, some of them are nonsyonymous , and some said unkown. may I check nonsyonymous and unknown firstly? or just input all genes to CADD or polyphen?
> (4) Mirage is for variant set and mirage-vs is for gene set. so firstly I ran mirage and found that there are 150(in your paper) variants set, and then run mirage-VS just like your paper did?
> Thank you!
> Best!
> Haizhu

Thanks for your questions. Let me try to respond as below, 
(1) You need to count these numbers, No.case, No.contr once you have annotations from annovar. 
(2) again it is up to you to define variant groups 
(3) In our analysis, we only consider nonsyonymous mutations. You have much freedom to choose the input data as mirage is very generic
(4) I don't know the goal of your analysis and couldn't give you more specific suggestions.  mirage-VS is for variant set and mirage for gene set.  

Let me know if you still have any concerns. 

Best, 

Shengtong.

**Comment by han16** [comment]
> I got this email from a user:
> 
> > In my data analysis,  I got the result by using annovar anova. I found that you annotate with several popular programs including PolyPhen, CADD and SIFT.  In my data analysis, I will do this step before mirage analysis?   I read your code about mirage, there are four columns( format of input data column 1:variant, 2,NO.variant in cases 3. No variant in control 4 variant group index). but I do not know where these columns come from? can you teach me?
> 
> @han16 we wrote on [this page](https://xinhe-lab.github.io/mirage/articles/mwe.html) "Variant groups can be user defined, usually depending on its annotations." but it seems too vague to be helpful to users. Is it correct if we change it to the following:
> 
> "Variant groups can be user defined, usually depending on its annotations. For example, in Han et al (2019+), we label as group `2` those variants with PolyPhen 194 score greater than 0.957, CADD score top 10% or SIFT score < 0.05; other variants are labelled group `1`"
> 
> Is this correct?

@gaow 
This is just a toy example data. In our analysis, group 2 is defined as rare LoF, i.e. LoF variants with AF<1%. ''We identify loss-of-function (LoF) variants as the union of stop loss, stop gain, frameshift indels and splice site substitutions``. 

Best, 

Shengtong.

**Comment by linnanqia** [comment]
Dear Shengtong, I will do the project immediately.  I hope I can the significant results.  If I have questions, I will ask you here.

**Comment by linnanqia** [comment]
Dear shengtong,  you told me that "You need to count these numbers, No.case, No.contr once you have annotations from annular" , what is annular? it is annotations tool. I applied annovar to do this annotation based on bim file. so I don't know how to obtain No.case, No.contr.  Thank you! Best regards!  Anna

**Comment by gaow** [comment]
@han16 I've updated [this page](https://xinhe-lab.github.io/mirage/articles/mwe.html) with some clarifications relevant to mirage package based on discussions in this ticket. @linnanqia  I believe the updated text should answer your questions.

**Comment by linnanqia** [comment]
I am very sorry. I still feel very confused about how to count the variants in cases or controls. for example, in vcf files, each row is gene, the column is the sample,  I guess whether it just add all the times when appear 0/1,1/2,1/2? it is the N.case or N.contr. I think  N.case is not equal to  AF by using plink --freq. is that right? Thank you!

**Comment by han16** [comment]
> I am very sorry. I still feel very confused about how to count the variants in cases or controls. for example, in vcf files, each row is gene, the column is the sample, I guess whether it just add all the times when appear 0/1,1/2,1/2? it is the N.case or N.contr. I think N.case is not equal to AF by using plink --freq. is that right? Thank you!

No.case is the number of rare alleles in cases at every loci and No.contr is number of rare alleles in control sample. We have toy example showing what the input data looks like https://xinhe-lab.github.io/mirage/articles/mwe.html. You may need to get these summary statistics from VCF file, whatever and restructure it to the desired data format.  

Shengtong.

**Comment by linnanqia** [comment]
Hi Shengtong,
     I just finished my data analysis. but I feel confused again. because I don't which value I should pay attention to. And I think I made mistake when I came back to read your article . It said that "MIRAGE is designed to analyze rare variant data from case-control studies. It requires only the counts 65 of each variant in cases and controls respectively, assuming that cases and controls are well-matched. An 66 important case is pedigree sequencing studies of parent-child trios, where transmitted and 67 non-transmitted variants from parents to affected children would be free of population structure, and can 68 be viewed as perfect case-control studies".  
The first question is what is "well matched"? I also confused about these numbers, 65,67,68. 
The second question is: what is transmitted data and non-transmitted? what is case and control data?  Your data  come from pedigree sequencing studies of parent-child trios. However, in my data analysis, I just applied person with disease as case group, healthy person as control group. I guessed  you applied "AA" and "Aa" as the case group and "aa" as the control group and all your data are ASD. 
the third question is how to  read the results of "mirage". I don't know how to report and explain my results.  I ran your example data. can you give us detailed data description about mirage_toy and how to explain the result.
The forth question is that" we define a 201 total of 5 × 3 × 10 = 150 overlapping variant sets ". can you teach me how to get the 150 overlapping variant sets?
I feel very sorry about so many question, I am a new user of "mirage". and Thank you for your patient response!
Best regards!
Anna

**Comment by linnanqia** [comment]
I think I should read your another article "Integrated Model of De Novo and Inherited Genetic Variants Yields Greater Power to Identify Risk Genes". Thank you!

**Comment by linnanqia** [comment]
Dear, can you tell me which value I should pay attention to? "BF.PP.gene", "delta.est", "delta.pvalue", "eta.est", "eta.pvalue", "BF.all". I just want to know which gene is the significant gene. 
the following is part of my result:
<img width="687" alt="1" src="https://user-images.githubusercontent.com/48764321/76046724-a6ba0580-5f9b-11ea-9dee-c07571449547.png">
<img width="341" alt="2" src="https://user-images.githubusercontent.com/48764321/76046778-d2d58680-5f9b-11ea-8e0b-6094e8368600.png">
<img width="327" alt="3" src="https://user-images.githubusercontent.com/48764321/76046834-f8629000-5f9b-11ea-9fb7-c41dcb2fd900.png">
I need your help! I hope i can receive your response !
Best regards!
Anna

**Comment by han16** [comment]
> Dear, can you tell me which value I should pay attention to? "BF.PP.gene", "delta.est", "delta.pvalue", "eta.est", "eta.pvalue", "BF.all". I just want to know which gene is the significant gene.
> the following is part of my result:
> <img alt="1" width="687" src="https://user-images.githubusercontent.com/48764321/76046724-a6ba0580-5f9b-11ea-9dee-c07571449547.png">
> <img alt="2" width="341" src="https://user-images.githubusercontent.com/48764321/76046778-d2d58680-5f9b-11ea-8e0b-6094e8368600.png">
> <img alt="3" width="327" src="https://user-images.githubusercontent.com/48764321/76046834-f8629000-5f9b-11ea-9fb7-c41dcb2fd900.png">
> I need your help! I hope i can receive your response !
> Best regards!
> Anna

If you are interested in significant genes, you should look at post.prob or BF of every gene, the higher value, the more significant. 

Shengtong.

**Comment by linnanqia** [comment]
Thank you! yesterday I see. I came back to read beta distribution and gamma distribution and so on.  Now I got the result again and knew how to explain them. Thank you!

**Comment by linnanqia** [comment]
Thank you!  I see. I came back to read beta distribution and gamma distribution and so on these days.  Now I got the result again and knew how to explain them. Thank you!
